import pandas as pd, numpy as np
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
ss = getSampleStyleSheet()
B = ParagraphStyle('b', parent=ss['BodyText'], fontSize=10.5, leading=15, spaceAfter=7, alignment=4)
H1 = ParagraphStyle('h1', parent=ss['Heading1'], fontSize=15, spaceBefore=12)
H2 = ParagraphStyle('h2', parent=ss['Heading2'], fontSize=12.5)
CAP = ParagraphStyle('c', parent=B, fontSize=9, leading=12, textColor=colors.HexColor('#333333'))
SM = ParagraphStyle('s', parent=B, fontSize=7.5, leading=9, alignment=0)
w = pd.read_csv('results/who_rpoB_scored.tsv', sep='\t')
mic = pd.read_csv('results/cryptic_solo_variant_mic.tsv', sep='\t')
at = pd.read_csv('results/rpoB_structural_atlas.tsv', sep='\t')
nov = pd.read_csv('results/G2_all_plausible_novel.tsv', sep='\t')
g12 = w[(w.grade <= 2) & w.protein_level]; g3 = w[(w.grade == 3) & w.protein_level]; g45 = w[(w.grade >= 4) & w.protein_level]
ok = int(g12.plausible.sum()); N = len(g12)
b = mic.dropna(subset=['score']); b3 = b[b.n_solo >= 3]
from scipy.stats import spearmanr
rho = spearmanr(b3.score, np.log2(b3.median_mic))
def P(t, s=B): return Paragraph(t, s)
def T(df, widths=None, fs=7.5):
    data = [[P(str(c), SM) for c in df.columns]] + [[P(str(v), SM) for v in r] for r in df.values.tolist()]
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dde6f0')), ('GRID', (0, 0), (-1, -1), 0.25, colors.grey), ('VALIGN', (0, 0), (-1, -1), 'TOP')]))
    return t
def F(path, cap, wd=6.3):
    from PIL import Image as I
    im = I.open(path); h = wd * im.height / im.width
    return [Image(path, width=wd * inch, height=h * inch), P(cap, CAP)]
s = []
s += [P('A locked structural rule explains WHO-graded rifampicin resistance in <i>Mycobacterium tuberculosis</i> rpoB and ranks clinical variants by drug-site proximity', ss['Title']),
      P('rpoB slice of the TB drug-resistance structural map. Open public data only; all code, manifests and results in the project repository (rpob/).', CAP), Spacer(1, 8)]
s += [P('Abstract', H1), P(f'Rifampicin (RIF) resistance in <i>M. tuberculosis</i> comes mostly from mutations in rpoB, the RNA polymerase beta subunit. The WHO 2023 mutation catalogue grades rpoB variants by statistical association with resistance, but a large share remain of uncertain significance. We asked whether one transparent, pre-registered structural rule - the minimum heavy-atom distance of the mutated residue to RIF in the <i>M. tuberculosis</i> RNAP-RIF crystal structure (PDB 5UHC), with a fixed 8.0 A cutoff - is enough to explain WHO grade-1/2 entries, and whether it flags uncertain clinical variants as candidate resistance mutations. The rule and all gates were committed to version control before any outcome data were downloaded. A positive control confirmed the numbering map (S450 2.43 A, H445 3.42 A, D435 3.14 A from RIF). The rule passed its validation gate: {ok} of {N} grade-1/2 entries ({100*ok/N:.1f}%, Wilson 95% CI 84.3-94.3%) lie within 8.0 A, against {100*g3.plausible.mean():.1f}% of grade-3 entries and 0 of {len(g45)} grade-4/5 protein-altering entries. The 13 misses all sit in the RRDR loop 8.4-12.1 A from the drug (N438, P439, G442, L443, K446). Applying the rule to 5,286 CRyPTIC isolates whose only rpoB protein change was a single variant, no grade-3 or uncatalogued variant met the pre-registered novel-candidate gate (&gt;=3 solo isolates, median MIC above the 0.5 mg/L ECOFF); four drug-site variants met the MIC criterion in single isolates only and are reported as thin. In an exploratory analysis, distance strongly tracked MIC across 53 variants with &gt;=3 solo isolates (Spearman rho = {rho.statistic:.2f}, p = {rho.pvalue:.1e}), and five grade-1/2 contact-residue variants (L430P, H445N, H445S, D435G, S450V) showed median MICs at or below the ECOFF, matching the known borderline class. The result is a validated structural atlas of 28 resistance residues, a negative result for novel discovery that is preserved as such, and a quantitative link between drug-site geometry and resistance level.')]
s += [P('Hypothesis', H1), P('H1: WHO grade-1/2 rpoB RIF-resistance entries concentrate at residues within 8.0 A of RIF in the <i>M. tuberculosis</i> RNAP-RIF structure, at a rate of at least 90%. H2: grade-3 or uncatalogued rpoB variants that meet the same structural criterion, and are the only rpoB protein change in at least three CRyPTIC isolates with median RIF MIC above the ECOFF, are candidate resistance mutations. H1 was the gate for any novel interpretation; H2 was evaluated only after H1 passed.')]
s += [P('1. Introduction', H1),
      P('Rifampicin is the backbone of first-line tuberculosis therapy, and resistance to it defines rifampicin-resistant and multidrug-resistant TB. RIF binds a pocket in the RNAP beta subunit next to the RNA exit channel and blocks extension of the nascent transcript beyond two to three nucleotides. Most clinical resistance maps to an 81-bp "rifampicin resistance determining region" (RRDR, codons 426-452 in <i>M. tuberculosis</i> numbering; 507-533 in <i>E. coli</i>), which molecular diagnostics such as Xpert MTB/RIF target.'),
      P('The WHO 2023 catalogue (second edition) grades each variant from 1 (associated with resistance) to 5 (not associated), using phenotype-genotype statistics on tens of thousands of isolates plus expert rules. Most rpoB rows are grade 3, uncertain significance. Structure-based approaches have been used before: Portelli et al. (2020) built machine-learning models from structural features to predict resistance beyond the RRDR; a 2022 Molecules study modelled clinical RpoB mutations against RIF binding; and structure-informed ML was revisited in 2024. Our aim differs in two ways. First, we test the simplest possible structural explanation, one distance cutoff fixed in advance, so its success or failure is directly interpretable and cannot be overfit. Second, we pre-register a success gate against the current WHO grades and a separate, stricter gate for novel claims on public clinical MIC data, and we report both honestly.'),
      P('Prior-art verdict: CROWDED. Closest works: Portelli et al. 2020, Sci Rep 10:18120 (https://www.nature.com/articles/s41598-020-74648-y); "The Structural Basis of M. tuberculosis RpoB Drug-Resistant Clinical Mutations on Rifampicin Drug Binding", Molecules 2022 (https://www.mdpi.com/1420-3049/27/3/885); structure-informed ML preprint 2024 (https://doi.org/10.1101/2024.08.15.608097). Context: the E. coli RIF-site deep mutational scan, Nature 2023 (https://www.nature.com/articles/s41586-023-06495-6).', CAP)]
s += [P('2. Methods', H1), P('2.1 Pre-registration', H2),
      P('The question, rule, thresholds and gates were written in GATES_LOCKED.md and committed as a standalone commit before any outcome data were fetched. A second standalone addendum, written before G1 was computed, defined how multi-residue in-frame entries are scored and recorded the G0 positive control. Git history in the repository independently shows gates, then data byte-lock, then addendum, then results. No threshold was changed after outcome data were seen.'),
      P('2.2 Data', H2),
      P('Structure: PDB 5UHC, the <i>M. tuberculosis</i> RNAP transcription initiation complex with RIF (ligand RFP 1201, bound to chain C, RpoB). Reference sequence: UniProt P9WGY9 (1178 aa); the WHO catalogue uses the 1172-aa H37Rv annotation, so WHO position = UniProt position - 6. Answer key: WHO 2023 catalogue master file (WHO-UCN-TB-2023.6), 1,502 rpoB rows for rifampicin. Clinical isolates: the CRyPTIC consortium release (Zenodo record 15680920), per-sample catalogue effects (EFFECTS table, 77,543 rpoB/RIF rows over 41,048 samples) and UKMYC5/6 RIF MICs (21,681 measurements). All files are listed with source URLs and SHA-256 checksums in rpob/data/DATA_MANIFEST.md.'),
      P('2.3 Structural rule', H2),
      P('Hydrogens were removed and, for every resolved RpoB residue, the minimum distance between any residue heavy atom and any RIF heavy atom was computed with gemmi and numpy. The structure sequence was globally aligned to UniProt residues 7-1178 (Biopython PairwiseAligner); all 1,126 resolved residues mapped with 100% identity, and 5UHC author numbering equals WHO numbering + 6. Residues at &lt;=4.5 A are "direct contact", 4.5-8.0 A "pocket shell" and &gt;8.0 A "distal". A residue is "resistance-plausible" at &lt;=8.0 A. In-frame deletions and delins are scored by the minimum over their span; insertions and duplications by their flanking or duplicated residues. Entries at unresolved residues count as failures.'),
      P('2.4 Gates', H2),
      P('G0 (positive control): S450, H445 and D435 must each lie within 6 A of RIF. G1 (validation): at least 90% of WHO grade-1/2 rpoB RIF entries must be resistance-plausible. G1b (reported): the plausible rate in grade-4/5 entries must be lower. G2 (novel candidates): a grade-3 or uncatalogued variant that is resistance-plausible, is the only rpoB protein-altering variant in at least 3 phenotyped CRyPTIC isolates, and has median MIC above the ECOFF. Variants meeting the MIC criterion in fewer than three isolates are reported as thin.'),
      P('2.5 CRyPTIC processing', H2),
      P('Per-sample rpoB calls were parsed: missense calls (e.g. S450L) were converted to HGVS and matched to WHO grades, synonymous, promoter and null (X) calls were dropped, and nucleotide indels were mapped to codons. An isolate is "solo" for a variant when that variant is its only rpoB protein-altering call. MICs were taken from UKMYC plates; censored values were set to half the lowest (&lt;=x) or twice the highest (&gt;x) concentration for medians. The ECOFF, 0.5 mg/L, is the highest MIC labelled S in the CRyPTIC binary phenotype (R begins at 1.0 mg/L). Isolates with no rpoB protein-altering call served as a wild-type reference.'),
      P('2.6 Mechanism atlas and exploratory analysis', H2),
      P('For each residue carrying a grade-1/2 entry we recorded the closest residue and RIF atoms, polar contacts within 3.5 A, and which RIF moiety is closest. Moieties were defined from the bond graph of the RFP chemical component (naphthofuranone core, ansa bridge, hydrazone-piperazine tail). The distance-MIC correlation was not pre-registered and is labelled exploratory throughout.')]
s += [P('3. Results', H1), P('3.1 Positive control (G0): pass', H2),
      P('The three canonical resistance residues sit in direct contact with RIF: S450 at 2.43 A, H445 at 3.42 A and D435 at 3.14 A. Twenty-one RpoB residues are within 4.5 A: 12 in the RRDR (S428-D435, H445, R448, S450, L452) and nine outside it (R167, V170, R459, P483, N487, I491, N604, R607, H674).')]
s += F('results/figures/fig1_distance_profile.png', 'Figure 1. Minimum heavy-atom distance from each resolved RpoB residue (150-700 shown) to RIF in 5UHC. WHO grade-1 (red), grade-2 (orange) and grade-3 (olive) entries are plotted at their scored distance. Dashed line: locked 8.0 A cutoff; dotted: 4.5 A contact threshold. Blue band: RRDR.')
s += [P('3.2 Validation (G1): pass', H2),
      P(f'Of {N} WHO grade-1/2 entries (103 missense, 27 in-frame deletions, 6 in-frame insertions), {ok} ({100*ok/N:.1f}%) were resistance-plausible: 89 direct contact, 34 pocket shell, 13 distal, none unresolved. The gate threshold was 90%, so the pass is narrow; a single additional miss would have failed it, and the lower bound of the 95% CI (84.3%) is below 90%. We report the pass as met but thin. The rule is selective: only {int(g3.plausible.sum())} of {len(g3)} grade-3 protein-altering entries ({100*g3.plausible.mean():.1f}%) and 0 of {len(g45)} grade-4/5 protein-altering entries are within 8.0 A (the other 552 grade-4/5 rows are synonymous or upstream).')]
t1 = pd.DataFrame([['Grade 1-2', N, (g12['class'] == 'contact').sum(), (g12['class'] == 'shell').sum(), (g12['class'] == 'distal').sum(), f'{100*g12.plausible.mean():.1f}%'],
                   ['Grade 3', len(g3), (g3['class'] == 'contact').sum(), (g3['class'] == 'shell').sum(), (g3['class'] == 'distal').sum(), f'{100*g3.plausible.mean():.1f}%'],
                   ['Grade 4-5', len(g45), 0, 0, len(g45), '0.0%']], columns=['WHO grade', 'Protein-altering entries', 'Contact <=4.5 A', 'Shell 4.5-8 A', 'Distal >8 A', 'Plausible (<=8 A)'])
s += [P('Table 1. Structural class of WHO 2023 rpoB RIF entries by grade (grade-3 total includes 17 unresolved/unscorable).', CAP), T(t1), Spacer(1, 8)]
s += F('results/figures/fig2_class_by_grade.png', 'Figure 2. Fraction of WHO entries in each structural class, by grade.', 4.8)
dis = g12[~g12.plausible][['variant', 'grade', 'score']].copy(); dis['variant'] = dis.variant.str.replace('rpoB_', '')
dis['score'] = dis.score.round(2)
expl = {438: 'RRDR loop; backbone links Q436/N437 shell to the P439 turn', 439: 'proline turn of the RRDR loop; likely repositions the S431-D435 contact segment', 442: 'glycine in loop; Glu adds bulk/charge next to shell residue S441', 443: 'hydrophobic loop residue packing behind H445 and T444', 446: 'lysine adjacent to H445; substitutions likely alter H445 side-chain placement'}
dis['structural explanation (hypothesis)'] = [expl[int(''.join(c for c in v.split('.')[1][3:] if c.isdigit())[:3])] for v in dis.variant]
s += [P('3.3 Discrepancies', H2), P('All 13 grade-1/2 entries outside 8.0 A fall at five RRDR residues, 8.4-12.1 A from RIF. None is far from the pocket in sequence; each sits in the loop that carries the contact residues D435 and H445. The most parsimonious explanation is second-shell effects on loop conformation, which a static distance rule cannot capture. These are hypotheses, not tested here, and the entries remain counted as failures.'),
      P('Table 2. The 13 grade-1/2 entries not explained by the 8.0 A rule.', CAP), T(dis, [1.6 * inch, 0.5 * inch, 0.6 * inch, 3.8 * inch])]
s += [P('3.4 Structural atlas', H2), P('Table 3 lists every residue that carries a WHO grade-1/2 entry, with its distance, the closest RIF moiety, polar contacts and the number of CRyPTIC solo isolates. Resistance burden is extremely concentrated: S450 (3,111 solo isolates), D435 (840) and H445 (588) account for most clinical resistance, all in direct contact with RIF. The contact residues split between the naphthofuranone core (Q429, L430, Q432, R448, S450, L452) and the ansa bridge (S428, S431, F433, M434, D435, H445, I491), consistent with RIF being held by both faces of the pocket.')]
at2 = at[['who_pos', 'ecoli_pos', 'aa', 'min_dist', 'rif_moiety', 'polar_contacts_le3_5A', 'n_grade12_entries', 'cryptic_solo_isolates', 'mechanism']].fillna('')
at2.columns = ['WHO pos', 'E. coli pos', 'aa', 'dist A', 'closest RIF moiety', 'polar contacts <=3.5 A', 'grade-1/2 entries', 'CRyPTIC solo isolates', 'class']
s += [P('Table 3. rpoB rifampicin structural atlas (residues carrying WHO grade-1/2 entries). E. coli numbering = WHO + 81.', CAP), T(at2, [0.45 * inch, 0.5 * inch, 0.4 * inch, 0.45 * inch, 1.0 * inch, 1.5 * inch, 0.55 * inch, 0.6 * inch, 0.95 * inch])]
s += F('results/figures/fig4_pocket_map.png', 'Figure 4. Two-dimensional principal-component projection of RIF heavy atoms (green) and CA atoms of residues within 12 A. Circle size and colour show the number of WHO grade-1/2 entries at each residue.', 5.2)
s += [P('3.5 Novel candidates (G2): none met the gate', H2),
      P(f'We identified 5,286 phenotyped CRyPTIC isolates carrying exactly one rpoB protein-altering variant, covering 155 distinct variants (24 grade 1, 34 grade 2, 82 grade 3, 4 grade 4-5, 11 uncatalogued). The wild-type reference (5,470 isolates with no rpoB protein change) had median MIC 0.06 mg/L and 4.6% were called resistant, which sets the background for phenotype noise and resistance from outside rpoB. Twelve grade-3 or uncatalogued variants were resistance-plausible and phenotyped. None met G2. The three with at least three solo isolates (P454L, n=5; I491M, n=4; S493W, n=3) all had median MICs below the ECOFF. Four met the MIC criterion in one isolate each (I491Y, S493R, and premature stops D435* and L452*); the stop calls are implausible in an essential gene and more likely reflect mixed populations or calling artefacts. Under the locked rule this is a negative result for novel discovery, and we do not relax the gate.')]
nv = nov[['MUTATION', 'status', 'score', 'class', 'n_solo', 'median_mic', 'frac_R']].copy(); nv['score'] = nv.score.round(2); nv['frac_R'] = nv.frac_R.round(2)
nv['G2 verdict'] = ['candidate' if (a >= 3 and m > 0.5) else ('thin (n<3)' if m > 0.5 else ('no MIC' if pd.isna(m) else 'below ECOFF')) for a, m in zip(nv.n_solo, nv.median_mic)]
s += [P('Table 4. All grade-3/uncatalogued resistance-plausible variants with CRyPTIC solo isolates.', CAP), T(nv)]
s += [P('3.6 Exploratory: distance tracks resistance level', H2),
      P(f'Across the 53 variants with at least three solo isolates, distance to RIF was strongly and inversely correlated with median MIC (Spearman rho = {rho.statistic:.2f}, p = {rho.pvalue:.1e}). Contact-residue variants had median MIC 8 mg/L and on average 72% of isolates resistant; distal variants had median MIC 0.06 mg/L and 1.6% resistant, matching wild type. This analysis was not pre-registered and uses CRyPTIC isolates that also contributed to the WHO catalogue, so it is not independent validation.'),
      P('Within the contact class, five grade-1/2 variants had median MIC at or below the ECOFF: L430P (n=98, median 0.25, 15% R), H445N (n=42, 0.25, 24% R), H445S (n=7), D435G (n=4) and S450V (n=3). This matches the low-level ("borderline") RIF resistance known for some RRDR mutations; we did not verify which of these five appear on the WHO borderline list, so that link remains a citation check. The structural rule places them in the pocket but does not predict their smaller effect, which points to a limit of distance-only models: the chemistry of the substitution matters as well as its location.')]
s += F('results/figures/fig3_mic_vs_distance.png', 'Figure 3. Median RIF MIC among solo isolates against the distance of the mutated residue to RIF, for variants with >=3 solo isolates. Point size scales with isolate count. Dashed line: ECOFF 0.5 mg/L; dotted line: 8.0 A.')
top = mic[mic.n_solo >= 20][['MUTATION', 'status', 'score', 'class', 'n_solo', 'n_high', 'median_mic', 'frac_R']].copy(); top['score'] = top.score.round(2); top['frac_R'] = top.frac_R.round(2)
s += [P('Table 5. CRyPTIC rpoB variants with >=20 solo phenotyped isolates.', CAP), T(top)]
s += [P('4. Discussion', H1),
      P('One fixed distance cutoff on a single crystal structure explains just over 90% of the rpoB mutations that WHO grades as associated with RIF resistance, and very few of those it grades as uncertain or not associated. That supports the simple mechanism most often assumed for RIF resistance: mutations act by changing the drug-binding pocket directly. The rule also tells us what it cannot explain. Its failures cluster in one loop segment, and its successes include borderline mutations with near-wild-type MICs. Both point to effects on loop dynamics and on the chemistry of specific contacts, which distance alone does not capture.'),
      P('The novel-discovery gate was not met. Under strict criteria, CRyPTIC contains no grade-3 variant at the drug site with enough solo isolates and high MICs to call it a resistance mutation. Part of the reason is circular: CRyPTIC isolates were part of the evidence base for the WHO 2023 grades, so a variant that is uncertain in the catalogue is likely to be rare or mixed in CRyPTIC too. Independent data (for example, later clinical collections not used by WHO) would be needed to test the thin candidates I491Y and S493R.'),
      P('Practical use. The atlas (Table 3, results/rpoB_structural_atlas.tsv) and the per-residue distance table (results/residue_distances.tsv) form a small lookup tool: given any new rpoB variant in WHO numbering, it returns the structural class, the closest RIF moiety and the CRyPTIC MIC evidence. Our data suggest that a new variant at a contact residue deserves phenotypic follow-up, while a distal variant is very unlikely to raise the MIC.'),
      P('Limitations. (1) One static structure, one ligand; no dynamics, no RIF analogues such as rifapentine or rifabutin. (2) The 8.0 A cutoff was chosen a priori, not optimised; other cutoffs were deliberately not tested, to avoid fishing. (3) The G1 margin is narrow and its CI crosses 90%. (4) The grade-4/5 protein-altering set has only 7 entries. (5) The CRyPTIC data overlap the WHO training data. (6) Compensatory mutations in rpoA/rpoC and non-rpoB resistance are out of scope. (7) The distance-MIC analysis is exploratory.')]
s += [P('5. Conclusion', H1), P(f'A transparent, pre-registered structural rule passed its validation gate against WHO 2023 grades ({ok}/{N}, {100*ok/N:.1f}%), produced a 28-residue mechanism atlas, and showed that distance to RIF tracks resistance level in public clinical data. It found no novel resistance mutations that pass a strict locked gate, and that negative result is reported as it stands.')]
s += [P('Data and code availability', H1), P('Repository tb-resistance-structural-map, directory rpob/: code/00-06 scripts, data/DATA_MANIFEST.md (sources and SHA-256), results/ tables and figures, GATES_LOCKED.md and GATES_ADDENDUM_1.md. Sources: RCSB PDB 5UHC; UniProt P9WGY9; WHO 2023 catalogue (github.com/GTB-tbsequencing/mutation-catalogue-2023); CRyPTIC (zenodo.org/records/15680920; ftp.ebi.ac.uk/pub/databases/cryptic).')]
s += [P('References', H1)] + [P(x, CAP) for x in [
    'World Health Organization. Catalogue of mutations in Mycobacterium tuberculosis complex and their association with drug resistance, 2nd ed. 2023. Master file: https://github.com/GTB-tbsequencing/mutation-catalogue-2023',
    'CRyPTIC Consortium. A data compendium associating the genomes of 12,289 Mycobacterium tuberculosis isolates with quantitative resistance phenotypes to 13 antibiotics. PLoS Biol 2022. https://doi.org/10.1371/journal.pbio.3001721',
    'RCSB PDB 5UHC: Crystal structure of Mycobacterium tuberculosis transcription initiation complex with rifampicin. https://www.rcsb.org/structure/5UHC',
    'Portelli S. et al. Prediction of rifampicin resistance beyond the RRDR using structure-based machine learning approaches. Sci Rep 2020. https://www.nature.com/articles/s41598-020-74648-y',
    'The Structural Basis of Mycobacterium tuberculosis RpoB Drug-Resistant Clinical Mutations on Rifampicin Drug Binding. Molecules 2022, 27(3):885. https://www.mdpi.com/1420-3049/27/3/885',
    'Predicting rifampicin resistance in M. tuberculosis using machine learning informed by protein structural and chemical features. bioRxiv 2024. https://doi.org/10.1101/2024.08.15.608097',
    'High-resolution landscape of an antibiotic binding site. Nature 2023. https://www.nature.com/articles/s41586-023-06495-6']]
s += [PageBreak(), P('Appendix A. All WHO 2023 grade-1/2 rpoB RIF entries with structural score', H1)]
ap = g12[['variant', 'grade', 'effect', 'score', 'class']].copy(); ap['variant'] = ap.variant.str.replace('rpoB_', ''); ap['score'] = ap.score.round(2)
s += [T(ap, [2.2 * inch, 0.6 * inch, 1.4 * inch, 0.8 * inch, 1.2 * inch])]
s += [P('Appendix B. Gate chronology (git)', H1), P(open('/tmp/gitlog.txt').read().replace('\n', '<br/>'), SM)]
doc = SimpleDocTemplate('paper/rpoB_structural_atlas_paper.pdf', pagesize=letter, leftMargin=0.8 * inch, rightMargin=0.8 * inch, topMargin=0.8 * inch, bottomMargin=0.8 * inch, title='rpoB rifampicin structural atlas')
doc.build(s, onLaterPages=lambda c, d: c.drawString(4 * inch, 0.45 * inch, str(d.page)))
