#!/usr/bin/env python3
"""06_paper.py - inhA slice paper PDF (reportlab), mirroring the rpob slice layout."""
import os, pandas as pd, numpy as np
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
R = os.path.join(os.path.dirname(__file__), '..', 'results')
os.chdir(os.path.join(os.path.dirname(__file__), '..'))
ss = getSampleStyleSheet()
B = ParagraphStyle('b', parent=ss['BodyText'], fontSize=10.5, leading=15, spaceAfter=7, alignment=4)
H1 = ParagraphStyle('h1', parent=ss['Heading1'], fontSize=15, spaceBefore=12)
H2 = ParagraphStyle('h2', parent=ss['Heading2'], fontSize=12.5)
CAP = ParagraphStyle('c', parent=B, fontSize=9, leading=12, textColor=colors.HexColor('#333333'))
SM = ParagraphStyle('s', parent=B, fontSize=7.5, leading=9, alignment=0)
def P(t, s=B): return Paragraph(t, s)
def T(df, fs=7.5):
    data = [[P(str(c), SM) for c in df.columns]] + [[P(str(v), SM) for v in r] for r in df.values.tolist()]
    t = Table(data, repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,0), colors.HexColor('#dde6f0')), ('GRID', (0,0), (-1,-1), 0.25, colors.grey), ('VALIGN', (0,0), (-1,-1), 'TOP')]))
    return t
def F(path, cap, wd=6.3):
    from PIL import Image as I
    im = I.open(path); h = wd * im.height / im.width
    return [Image(path, width=wd*inch, height=h*inch), P(cap, CAP)]

who = pd.read_csv(os.path.join(R,'who_inhA_scored.tsv'), sep='\t')
at = pd.read_csv(os.path.join(R,'inhA_structural_atlas.tsv'), sep='\t')
mi = {d: pd.read_csv(os.path.join(R,f'cryptic_solo_variant_mic_{d}.tsv'), sep='\t') for d in ('INH','ETH')}
ci = pd.read_csv(os.path.join(R,'G2_candidates_INH.tsv'), sep='\t'); ce = pd.read_csv(os.path.join(R,'G2_candidates_ETH.tsv'), sep='\t')
ti = pd.read_csv(os.path.join(R,'G2_thin_INH.tsv'), sep='\t'); te = pd.read_csv(os.path.join(R,'G2_thin_ETH.tsv'), sep='\t')
g3 = who[(who.protein_level)&(who.grade==3)]; g45 = who[(who.protein_level)&(who.grade>=4)]
from scipy.stats import spearmanr
m3 = mi['INH']; m3 = m3[m3.n_solo>=3].dropna(subset=['score'])
rho = spearmanr(m3.score, np.log2(m3.median_mic))

s = []
s += [P('A locked structural rule on the InhA - isonicotinic-acyl-NAD complex validates the WHO-graded isoniazid/ethionamide target mutation and ranks clinical InhA variants by adduct-site proximity', ss['Title']),
      P('inhA slice of the TB drug-resistance structural map. Open public data only; all code, manifests and results in the project repository (inha/).', CAP), Spacer(1,8)]
s += [P('Abstract', H1),
      P(f'Isoniazid (INH) and ethionamide (ETH) are prodrugs whose activated forms covalently modify NAD in the active site of InhA, the enoyl-ACP reductase of <i>M. tuberculosis</i>. The WHO 2023 mutation catalogue grades inhA variants by statistical association with resistance, but most coding rows remain of uncertain significance, and its high-confidence resistance set for this target is dominated by promoter (upregulation) variants that no protein structure can score. We asked whether one transparent, pre-registered structural rule - heavy-atom distance of the mutated residue to the INH-NAD adduct in PDB 1ZID (fixed 8.0 A cutoff), plus fixed catalytic-anchor and buried-destabilizing clauses - reproduces the WHO grade-1/2 coding assignments, and whether it flags uncertain clinical variants as candidates. The rule and gates were committed to version control before any outcome data were fetched; the lane record carries a contamination note from a prior builder, so the full lock-before-results chain is preserved in commit order and disclosed in the pre-registration. The only WHO grade-1/2 coding variant, S94A, sits 3.48 A from the adduct: G1 passes (1/1) but is thin by construction, and we report it as such. The rule is selective: 33.1% of grade-3 coding entries and 0% of grade-4/5 coding entries are flagged. Applying the locked rule to CRyPTIC isolates carrying a single inhA/fabG1 coding variant, seven variants met the pre-registered novel-candidate gate for INH (>=3 solo isolates, median MIC above the 0.1 mg/L ECOFF): I194T (n=34, median 3.2 mg/L), T162S, E196A, P12R, I21V, I21T and A190S; two (I194T, I21T) met it for ETH (ECOFF 4.0 mg/L). Distance tracked MIC across INH solo variants (Spearman rho = {rho.statistic:.2f}, p = {rho.pvalue:.1e}, exploratory). The result is a validated structural atlas of InhA resistance neighborhoods, candidate upgrades for six WHO grade-3 variants, and a clear statement of what structure cannot grade: the operon promoter.')]
s += [P('Hypothesis', H1),
      P('H1: WHO grade-1/2 inhA coding resistance entries for INH/ETH concentrate at residues within 8.0 A of the INH-NAD adduct, or satisfy the fixed catalytic-anchor / buried-destabilizing clauses, at a rate of at least 90%. H2: grade-3 or uncatalogued inhA coding variants meeting the same structural criterion, carried as the sole inhA/fabG1 protein-altering variant in at least three CRyPTIC isolates with median MIC above the drug ECOFF, are candidate resistance mutations. H1 gated any novel interpretation; H2 was evaluated only after H1 passed. Promoter variants were pre-registered as out of structural scope and reported on a separate descriptive line.')]
s += [P('1. Introduction', H1),
      P('INH is a cornerstone of tuberculosis therapy; ETH is its second-line thioamide analogue. Both are prodrugs: INH is activated by the catalase-peroxidase KatG, ETH by the monooxygenase EthA, and the activated species reacts with NAD(H) to form an adduct that inhibits InhA, blocking mycolic acid synthesis. Because both drugs converge on InhA, inhA coding mutations and upregulation of the fabG1-inhA operon produce cross-resistance to both drugs - the reason the WHO catalogue grades inhA variants against both INH and ETH.'),
      P('The WHO 2023 catalogue (second edition) grades each variant 1 (associated with resistance) to 5 (not associated). For inhA, the high-confidence resistance set is unusual: of 16 grade-1/2 rows (INH and ETH), 14 are upstream (promoter) variants and only one unique coding variant - S94A - reaches grade 1/2. The canonical clinical markers I21T and I194T sit at grade 3, uncertain significance, despite strong mechanistic literature. Structure-based in silico studies of InhA resistance exist but use small hand-picked mutation sets with docking or molecular dynamics, and none validate at catalogue scale against a locked gate.'),
      P('Prior-art verdict: CROWDED (niche remains). Closest works: a PLOS One 2015 molecular-dynamics study of INH-resistant InhA mutants (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144635); a Biophysical Journal 2005 MD study of I21V and I16T (https://www.cell.com/biophysj/fulltext/S0006-3495(05)72739-9); an integrated computational InhA mutation study, J Mol Graph Model 2020 (https://www.sciencedirect.com/science/article/abs/pii/S109332632030557X); a thermodynamic-integration MD study of INH/ETH cross-resistance (https://research.mpu.edu.mo/en/publications/thermodynamic-integration-combined-with-molecular-dynamic-simulat/); and a broad in silico survey of DR mutations in Mtb (https://pmc.ncbi.nlm.nih.gov/articles/PMC12703862/). Our angle: catalogue-scale, validation-first, a locked transparent rule with no fitted parameters, then novel candidates on public clinical MIC data.', CAP)]
s += [P('2. Methods', H1), P('2.1 Pre-registration and integrity', H2),
      P('The question, rule, thresholds and gates were written in inha/GATES_LOCKED.md and committed as a standalone commit (8ea16ec, 2026-10-08 19:01 IST) before any outcome data were fetched. Two addenda followed the rpob-slice pattern: addendum 1 (8ea202d) fixed operational definitions and recorded the G0 positive control before G1 was computed; addendum 2 (bcd9baf) corrected the descriptive promoter-class mapping and is disclosed as informed by observed variant positions (the promoter line is descriptive and never gated). The lane record carries a contamination note: a prior B07 builder may have seen WHO inhA grades before any gate lock ("even though a previous builder already peeked"). This builder states that no WHO inhA/fabG1 row or CRyPTIC INH/ETH phenotype was downloaded or inspected before the gates commit, and the git commit order - gates, data byte-lock (9591ba4), addendum, results (b9874e3) - is the proof of lock-before-results. No threshold was changed after outcome data were seen.'),
      P('2.2 Data', H2),
      P('Structure: PDB 1ZID, <i>M. tuberculosis</i> InhA in complex with the isonicotinic-acyl-NAD inhibitor (ligand ZID 300; chain A, residues 2-269 resolved; 2.70 A). Supporting: PDB 2IDZ, wild-type InhA with the same adduct at 2.0 A; PDB 4TZK (1.62 A) for cross-checks. Reference sequence: UniProt P9WGR1 (INHA_MYCTU, 269 aa); the 1ZID DBREF accession P0A5Y6 is retired. Answer key: WHO 2023 catalogue master file (WHO-UCN-TB-2023.6), 520 rows with gene inhA for INH or ETH. Clinical isolates: CRyPTIC (Zenodo record 15680920) per-sample catalogue effects (23,494 inhA/fabG1 rows over 10,452 samples for INH and ETH) and UKMYC MICs (43,363 INH/ETH measurements). All files are listed with URLs and SHA-256 checksums in inha/data/DATA_MANIFEST.md; the WHO master checksum matches the rpob slice record.'),
      P('2.3 Locked rule', H2),
      P('Hydrogens were removed; for every resolved chain-A residue the minimum heavy-atom distance to the ZID adduct was computed (Biopython + numpy). Classes: direct contact <=4.5 A, pocket shell 4.5-8.0 A, distal >8.0 A. A coding variant is STRUCT-R if any of: R1, its residue is within 8.0 A of the adduct; R2, it is one of the fixed catalytic/adduct anchors {S94, Y158, K165}; R3, it is buried (Shrake-Rupley RSA < 0.20 on the protein-only monomer) and destabilizing (net formal-charge change, proline gain/loss, or |delta volume| > 80 A^3, Zamyatnin volumes). R0 (loss-of-function mirroring) had no instances: the WHO subset contains only missense, synonymous and upstream rows. WHO/H37Rv numbering equals structure numbering (offset 0); the only sequence mismatch is the N-terminal cloning artifact T2A, excluded from atlas claims.'),
      P('2.4 Gates', H2),
      P('G0 (positive control): S94, Y158, K165 must each lie within 6 A of the adduct. G1 (validation): >=90% of unique WHO grade-1/2 coding variants (union across drugs) labeled STRUCT-R; unresolved residues count as failures; grade 3 reported separately. G1b (reported): STRUCT-R rate among grade-4/5 coding entries. G2 (novel candidates): grade-3 or uncatalogued STRUCT-R variants, sole inhA/fabG1 protein-altering variant in >=3 phenotyped CRyPTIC isolates, median MIC above the ECOFF; sub-threshold counts reported as thin. All grade-1/2 misses documented; failure would have been reported as a negative without re-fishing.'),
      P('2.5 CRyPTIC processing', H2),
      P('Per-sample inhA/fabG1 calls were parsed; synonymous and null calls were dropped, upstream calls (e.g. c-15t) were tracked separately and disqualified isolates from "solo" status. An isolate is solo for a variant when it is its only inhA/fabG1 protein-altering call and it carries no inhA/fabG1 upstream call. MICs come from UKMYC plates; censored values were set to half (<=x) or twice (>x) the bound. The ECOFF is data-derived per drug: the highest MIC labelled S in the CRyPTIC binary phenotype (INH 0.1 mg/L; ETH 4.0 mg/L). The distance-MIC correlation is exploratory, not pre-registered.')]
s += [P('3. Results', H1), P('3.1 Positive control and fidelity (G0): pass', H2),
      P('Chain A of 1ZID spans residues 2-269 and matches P9WGR1 except the T2A cloning artifact. The three canonical catalytic/adduct residues sit in direct contact with the adduct: S94 at 3.48 A, Y158 at 3.80 A and K165 at 2.88 A - all under the 6 A bound, so the numbering map is correct. Per-residue adduct distances from the 2.0 A wild-type structure 2IDZ agree with 1ZID to a mean absolute difference of 0.40 A (r = 0.997 over 268 residues), so the 2.7 A primary structure does not distort the geometry.')]
s += F('results/figures/fig1_distance_profile.png', 'Figure 1. Minimum heavy-atom distance from each resolved InhA residue to the INH-NAD adduct (ZID) in 1ZID. Red: the WHO grade-1/2 coding variant (S94A). Olive: grade-3 coding entries. Dashed line: locked 8.0 A cutoff; dotted: 4.5 A contact threshold.')
s += [P('3.2 Validation (G1): pass, thin by construction', H2),
      P(f'The WHO 2023 inhA subset holds 520 rows (grades: 1: 3, 2: 13, 3: 379, 4: 121, 5: 4). The 16 grade-1/2 rows split into 14 upstream (promoter) rows and one unique coding variant, S94A, graded 2 for both INH and ETH. S94A lies 3.48 A from the adduct and satisfies R1 and R2, so G1 passes at 1/1 = 100%. The pass is thin by construction - the catalogue itself assigns high confidence to only one coding variant for this target - and we report it as such rather than inflating it. The rule is selective: {int((g3.STRUCT_R==True).sum())} of {len(g3)} grade-3 coding entries ({100*(g3.STRUCT_R==True).mean():.1f}%) and 0 of {len(g45)} grade-4/5 coding entries are STRUCT-R.')]
t1 = pd.DataFrame([['1-2','1','1','0','0','100%'],
                   ['3', str(len(g3)), str(int(((g3.STRUCT_R==True)&(g3.score<=4.5)).sum())), str(int(((g3.STRUCT_R==True)&(g3.score>4.5)).sum())), str(int((g3.STRUCT_R!=True).sum())), f'{100*(g3.STRUCT_R==True).mean():.1f}%'],
                   ['4-5', str(len(g45)), '0','0', str(len(g45)), '0.0%']],
                  columns=['WHO grade','coding entries','STRUCT-R contact','STRUCT-R shell','STRUCT-neutral','STRUCT-R rate'])
s += [T(t1), P('Table 1. Locked-rule labels by WHO grade for inhA coding entries (row level, both drugs pooled).', CAP)]
s += [P('3.3 The promoter line: structure cannot grade the dominant mechanism', H2),
      P('Fourteen of the 16 grade-1/2 rows are upstream variants, and the grade-1 entries (c.-777C>T for both drugs; c.-154G>A for INH) are regulatory. c.-777C>T is the canonical fabG1 c.-15C>T operon-promoter mutation (mapping derived from the WHO genomic-position column; addendum 2): upregulation of the fabG1-inhA operon titrates the drug - a mechanism no protein structure can score. These variants were pre-registered as out of structural scope and are reported only descriptively. This is the central structural finding of the slice: for inhA, unlike katG or rpoB, the WHO high-confidence resistance signal is mostly regulatory, and a protein-structure rule addresses only the coding residue.')]
prom = pd.DataFrame([['c.-770T>A/C/G','2','INH+ETH','in class (fabG1 -8)'],
                     ['c.-777C>T','1','INH+ETH','in class (fabG1 -15, canonical)'],
                     ['c.-778A>G','2','INH+ETH','in class'],
                     ['c.-779G>T','2','INH+ETH','in class'],
                     ['c.-154G>A','1 (INH) / 2 (ETH)','INH+ETH','outside operon-promoter class; inside fabG1 CDS by mapping']],
                    columns=['WHO variant','grade','drugs','promoter-class note'])
s += [T(prom), P('Table 2. Grade-1/2 upstream variants (descriptive line; never gated). Positions are WHO c. numbering relative to the inhA start codon.', CAP)]
s += [P('3.4 Grade-3 triage and novel candidates (G2)', H2),
      P(f'In CRyPTIC, 191 phenotyped isolates carry a single inhA/fabG1 coding variant with no upstream call; 47 distinct variants have solo MIC evidence ({mi["INH"].n_solo.notna().sum() and len(mi["INH"])} for INH, {len(mi["ETH"])} for ETH). Seventeen grade-3 or uncatalogued variants are STRUCT-R. Seven met the locked novel-candidate gate for INH (n >= 3 solo isolates, median MIC > 0.1 mg/L ECOFF); two met it for ETH (ECOFF 4.0 mg/L). I194T - a canonical clinical marker sitting at WHO grade 3 - is carried solo by 34 isolates with median INH MIC 3.2 mg/L (97 pct R) and median ETH MIC 16 mg/L (94 pct R). I21T meets the gate for both drugs (n=5). Four INH and two ETH variants met the MIC criterion in fewer than three isolates and are reported as thin, not findings.')]
cols = ['MUTATION','hgvs','status','score','class','n_solo','n_high','median_mic','frac_R']
ci2 = ci[cols].rename(columns={'median_mic':'median INH MIC','frac_R':'frac R'})
s += [T(ci2), P('Table 3. G2 novel candidates for INH (locked gate: STRUCT-R, >=3 solo isolates, median MIC > 0.1 mg/L ECOFF).', CAP)]
ce2 = ce[cols].rename(columns={'median_mic':'median ETH MIC','frac_R':'frac R'})
s += [T(ce2), P('Table 4. G2 novel candidates for ETH (ECOFF 4.0 mg/L).', CAP)]
thin_all = pd.concat([ti.assign(drug='INH'), te.assign(drug='ETH')])[['MUTATION','hgvs','status','score','class','n_solo','median_mic','drug']]
s += [T(thin_all), P('Table 5. Thin variants: MIC criterion met in fewer than three solo isolates - documented, not findings.', CAP)]
s += F('results/figures/fig2_rule_by_grade.png', 'Figure 2. Locked-rule selectivity: STRUCT-R fraction across WHO grade classes for coding entries. The rule fires on the single grade-1/2 coding variant and on a minority of grade-3 entries, and never on grade-4/5.')
s += F('results/figures/fig3_mic_vs_distance.png', f'Figure 3. Median solo-isolate MIC vs adduct distance for variants with >=3 solo isolates. INH: Spearman rho = {rho.statistic:.2f}, p = {rho.pvalue:.1e} (exploratory). Dashed line: locked 8.0 A cutoff. Canonical clinical markers annotate directly.')
s += [P('3.5 Mechanism atlas', H2),
      P('The atlas (results/inhA_structural_atlas.tsv) covers all 268 resolved residues: adduct distance, mechanism class, RSA, WHO-graded variants at the residue, and CRyPTIC solo-isolate MIC statistics for both drugs. Eleven residues carrying WHO-graded entries are direct-contact (<4.5 A) and a further thirteen are pocket-shell; the contact set clusters on the nicotinamide half of the adduct (residues 15-22, 40-42, 94-95) and the substrate pocket rim (155-165, 189-194), exactly the neighborhoods the resistance literature names.')]
s += F('results/figures/fig4_pocket_map.png', 'Figure 4. Structural neighborhoods: adduct distance vs solvent accessibility for all resolved residues. Red: residues carrying a WHO-graded coding entry. The locked rule combines the distance clauses (vertical line) with the buried-destabilizing clause (below the dotted line).')
atlas_head = at[at.best_grade.notna()].head(40)[['who_pos','resname','min_dist','mech_class','best_grade','who_variants']]
s += [T(atlas_head), P('Table 6 (continues over pages). Atlas excerpt: the 40 closest residues carrying WHO-graded coding entries (of 80 such residues; full table in results/inhA_structural_atlas.tsv).', CAP)]

g3flag = g3[g3.STRUCT_R == True].copy()
g3flag['pos'] = g3flag.pos_start.astype(int)
tr = g3flag.merge(at[['who_pos','resname','mech_class']], left_on='pos', right_on='who_pos', how='left')
tr = tr[['variant','drug','resname','pos','score','mech_class']].drop_duplicates(subset=['variant','drug'])
tr.columns = ['WHO variant','drug','WT res','pos','dist (A)','class']
s += [T(tr), P('Table 7. Grade-3 (uncertain) coding entries flagged STRUCT-R by the locked rule - the triage list the atlas hands to future catalogues. Entries at the same residue share one structural interpretation.', CAP)]
s += [P('3.6 What the rule says about the canonical markers', H2),
      P("I21T (2.78 A, contact) and I194T (2.94 A, contact) are the slice's central triage result: both are WHO grade 3, both are direct-contact residues on the nicotinamide half of the adduct, and both meet the locked novel-candidate gate with multi-isolate MIC evidence for both drugs where phenotypes exist. S94A (3.48 A) is the catalogue's lone confident coding variant. The structural picture unifies all three: the adduct's nicotinamide-ribose pocket is the resistance epicenter, and the catalogue's uncertainty tier is populated largely by variants at exactly these distances.")]
s += [P('4. Discussion', H1),
      P('Three findings stand out. First, the WHO catalogue itself tells a structural story by subtraction: for inhA it is confident about regulation (promoter up variants) and about exactly one coding variant, S94A, which sits in direct contact with the adduct. A structure-only rule therefore cannot replicate katG- or rpoB-style catalogue concordance for this target, because most of the answer key is outside protein space; the honest G1 statement is "1/1, thin by construction", and we report it exactly so. Second, the same locked rule reorganizes the uncertain tier usefully: the grade-3 variants it flags are not random - I194T and I21T, the two canonical clinical markers the literature has long associated with low-level INH and ETH resistance, are direct-contact residues with strong solo-isolate MIC evidence (I194T: 34 isolates, 97 pct R, median 32x the INH ECOFF; I21T: 5 isolates, median 16x). Under the pre-registered G2 gate, seven INH and two ETH variants earn candidate status, including uncatalogued E196A and P12R; all are documented with their isolate counts and MICs. Third, adduct distance tracks MIC level across variants (INH Spearman rho %.2f), an exploratory quantitative link between adduct-site geometry and resistance level, echoing the rpoB slice.' % float(rho.statistic)),
      P('Limitations. The coding answer key is n=1, so G1 carries no statistical power; the G2 gate is the slice\'s real evidentiary weight, and its counts are modest (n=3-34). Solo status is defined within inhA/fabG1 only: katG, ethA and other-locus resistance variants are not excluded, so candidate MICs can be confounded by co-resistance - I194T isolates in particular often carry katG S315T in clinical populations, and our ETH candidates may ride on ethA backgrounds. The ECOFF is data-derived (highest S-labeled MIC), not a clinical breakpoint. P12R is flagged by the buried-destabilizing clause at 8.83 A - just beyond the distance cutoff - and its candidate status should be read with that in mind. The 1ZID construct carries the T2A N-terminal artifact, excluded from claims. Promoter variants are structurally unscoreable by design; a complete inhA resistance predictor needs a regulatory track this slice does not attempt.'),
      P('Integrity note. The lane record documents that a prior builder may have seen WHO inhA grades before any gate existed. This slice therefore preserves the entire chain in commit order - locked gates (8ea16ec) before data byte-lock (9591ba4) before addenda (8ea202d, bcd9baf) before results (b9874e3) - and discloses the contamination note in the pre-registration itself. The one outcome-informed correction (addendum 2, promoter-class mapping) touches only the descriptive promoter line and is labeled as such.')]
s += [P('5. Data and code availability', H1),
      P('All inputs are public: RCSB PDB (1ZID, 2IDZ, 4TZK, ligand ZID), UniProt P9WGR1, the GTB-tbsequencing WHO-UCN-TB-2023.6 master file, and the CRyPTIC Zenodo record 15680920 with the EBI GENOMES table. Checksums, URLs and derived-file recipes are in inha/data/DATA_MANIFEST.md; code is in inha/code/ (00_extract through 06_paper); results and figures are in inha/results/. Payload checksums are recorded in inha/MANIFEST.sha256 and the top-level MANIFEST.sha256.')]
doc = SimpleDocTemplate('paper/inhA_structural_atlas_paper.pdf', pagesize=letter, topMargin=0.8*inch, bottomMargin=0.8*inch)
doc.build(s)
print('paper pages written')
